language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12'
deploy:
  skip_cleanup: true
  on:
    repo: iamolegga/nestjs-roles
    branch: master
  provider: npm
  email: iamolegga@gmail.com
  api_key:
    secure: k252fr13F7FW/LrXmAWLww39aceAJgGo1Wg8PLXHajUWWMDF2Zqbk1u2f1O8LHLa5l5vrMAlst7hN38612VtJk5j4ZbywCuPvUiBy+25K+fvtEQ/z2dGKRHPHPgXKdA9MyJazQSiFrRstIJ/+/OTf9aGGPUhXTGp/bh93RVfxwVEpS7Pe8xsNHqpcLzrzeNINVibk5f5CH8VIwuRix8Twpi9pxQmnv2udhrS8pINqSfi1XqUu4FyTwChpwi+LuZOvHMTGGm21NMIumvBUJNHeRw3gS/u7pBmxqIyzrZVHah6iUMQmwUeYNKCNLq6Ew+QwMNO/NHMFL9GPnDq1pG5rWyLFyDxoQ8893m8apQVEmrmAHCImczHftB9HGlvOGr+tSc3DSiDrUWBnObsNrxbh+kVA4WMuhlxJqHde2wNWpYHUB7Fwi2STxSm9Nlz2+e8eU4I6RpYV5Ifhg11ZXYVtahiq8/cesvdDhasPfKsuHYtxSogGL6D0Viy8hIzh94RK6csjfyg2qxYThT2wpLk3Rxo9kp40Da5Ik1Ci1eV6hD3Nr1rLAs5a1n3rMbucWyZTMEZX2zd6r3dgR7WgkOwt/q7j4uyiTBkaXAvBJm3Zrf0uazeb48wOtfpgrH9wpn1ud4W9SjWuLlIgxFZad2ivgb1DrhRxVLvmSUtKTu/i9c=
script:
  - npm run build
  - npm run test
after_deploy:
  - npm run report
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
